import type { Rule } from './rules';

/**
 * The Indian merchant pack: brands and billers as they appear in bank narrations, by what they are. Checked before
 * the general word rules, so a specific name wins over a word it contains (Swiggy Instamart is groceries, not food;
 * "YouTube Premium" is a subscription, not insurance). Measured by test/exam/merchants.exam.ts.
 */
const R = (re: RegExp, category: string, kind: Rule['kind'] = 'spend'): Rule => ({ re, kind, category });

/** Money going into investments (either way: buying or redeeming). */
export const PACK_INVEST: Rule[] = [
  R(/\bPPFAS\b|PARAG ?PARIKH|NIPPON ?(INDIA )?(MF|MUTUAL)|MIRAE ?ASSET|AXIS ?(MF|MUTUAL)|HDFC ?(MF|MUTUAL)|SBI ?(MF|MUTUAL)|SBIMF|ICICI ?PRU(DENTIAL)? ?(MF|MUTUAL)|KOTAK ?(MAHINDRA )?(MF|MUTUAL)|\bDSP ?(MF|MUTUAL|INVESTMENT)|UTI ?(MF|MUTUAL|AMC)|QUANT ?(MF|MUTUAL)|MOTILAL ?OSWAL ?(MF|MUTUAL|AMC)|EDELWEISS ?(MF|MUTUAL)|TATA ?(MF|MUTUAL)|ADITYA ?BIRLA ?SUN ?LIFE ?(MF|MUTUAL|AMC)|\bABSL ?(MF|AMC)|FRANKLIN ?TEMPLETON|INVESCO ?(MF|MUTUAL)|CANARA ?ROBECO|BANDHAN ?(MF|MUTUAL)|HSBC ?(MF|MUTUAL)|NAVI ?(MF|MUTUAL)|WHITEOAK|360 ?ONE ?(MF|AMC)|GROWW\.ICCL|\bMFCENTRAL|\bMF ?UTILIT/, 'Mutual Funds', 'investment'),
];

export const PACK: Rule[] = [
  // subscriptions (before insurance's "premium" and shopping's "Amazon")
  R(/GOOGLE ?PLAY|YOUTUBE ?PREMIUM|JIO ?HOTSTAR|TIMES ?PRIME|SWIGGY ?ONE|ZOMATO ?GOLD|\bCANVA\b|GITHUB|GITLAB|\bFIGMA\b|ZOOM\.US|ZOOM ?VIDEO|\bSLACK\b|ATLASSIAN|JETBRAINS|AMAZON ?WEB ?SERVICES|\bAWS\b|GOOGLE ?CLOUD|GOOGLE ?WORKSPACE|DIGITALOCEAN|HEROKU|VERCEL|NETLIFY|GODADDY|HOSTINGER|NAMECHEAP|\bCURSOR\b|MIDJOURNEY|PERPLEXITY|GRAMMARLY|DUOLINGO|HEADSPACE|\bKINDLE\b|\bGAANA\b|\bWYNK\b|SAAVN|SUN ?NXT|ALT ?BALAJI|EROS ?NOW|DISCOVERY ?PLUS|APPLE ?MEDIA|APPLE\.COM|\bAHA ?(VIDEO|OTT)\b/, 'Subscriptions'),
  // groceries and quick commerce (before food: Instamart, Licious)
  R(/INSTAMART|SMART ?BAZAAR|\bLULU\b|\bSPAR\b|STAR ?BAZAAR|HYPER ?MARKET|RATNADEEP|EASYDAY|NILGIRIS|HERITAGE ?FRESH|\bLICIOUS\b|FRESH ?TO ?HOME|\bFTH\b|MILK ?BASKET|BB ?DAILY|\bDUNZO\b|\bOTIPY\b|SUPR ?DAILY|AKSHAYAKALPA|VIJETHA|NAMDHARI|FOODHALL|NATURES ?BASKET|\bMORE ?(SUPERMARKET|MEGASTORE)|\bSWIGGY ?GENIE/, 'Groceries'),
  // food
  R(/\bBOX8\b|FAASOS|BEHROUZ|OVENSTORY|REBEL ?FOODS|FRESH ?MENU|THEOBROMA|CHAI ?POINT|BLUE ?TOKAI|THIRD ?WAVE|TACO ?BELL|PIZZA ?HUT|NATURALS ?ICE|KRISPY ?KREME|BIRYANI ?BY ?KILO|\bPARADISE\b|MEGHANA|ABSOLUTE ?BARBECUE|BARBEQUE ?NATION|JUBILANT ?FOOD|DEVYANI|SAPPHIRE ?FOODS|WESTLIFE|RESTAURANT ?BRANDS|HARDCASTLE|\bMOJO ?PIZZA|LA ?PINOZ|BURGER ?SINGH|GOLI ?VADA|KWALITY ?WALLS|HAVMOR|AMUL ?PARLOUR/, 'Food & Dining'),
  // health (before shopping's "stores")
  R(/WELLNESS ?FOREVER|TRUEMEDS|HEALTHKART|CULT\.?FIT|CUREFIT|HEALTHIFYME|LAL ?PATH|METROPOLIS|THYROCARE|\bSRL\b|REDCLIFFE|ORANGE ?HEALTH|MEDIBUDDY|MEDPLUS|NARAYANA ?HEALTH|MANIPAL ?HOSP|MAX ?HEALTHCARE|CLOVE ?DENTAL|\bMEDICOS?\b|\bMEDICALS?\b|DAVAKHANA|DAWAKHANA|PHARMACY/, 'Health'),
  // shopping
  R(/\bBOAT\b|IMAGINE ?MARKETING|PURPLLE|MAMAEARTH|SNAPDEAL|SHOPSY|LIMEROAD|BEWAKOOF|SOULED ?STORE|PEPPERFRY|URBAN ?LADDER|WAKEFIT|HOME ?CENTRE|CHUMBAK|SKECHERS|\bPUMA\b|ADIDAS|\bNIKE\b|LEVI|MANYAVAR|FABINDIA|\bBIBA\b|CAMPUS ?ACTIV|LIBERTY ?SHOES|ONEPLUS|XIAOMI|SAMSUNG ?(INDIA|STORE)|RELIANCE ?TRENDS|\bTATA ?NEU|AMAZON ?PAY|CARATLANE|MALABAR ?GOLD|KALYAN ?JEWEL|\bGIVA\b|DUROFLEX|SLEEPYCAT/, 'Shopping'),
  // getting around
  R(/\bYULU\b|\bBOUNCE\b|\bVOGO\b|ZOOMCAR|\bREVV\b|DRIVEZY|\bMERU\b|QUICK ?RIDE|\bBMTC\b|\bBEST ?(BUS|UNDERTAKING)|MUMBAI ?METRO|NAMMA ?METRO|BMRCL|KOCHI ?METRO|\bHMRL\b|\bCMRL\b|\bPORTER\b|\bINDRIVE\b|BLABLACAR/, 'Transport'),
  // travel
  R(/ABHIBUS|THOMAS ?COOK|\bSOTC\b|HAPPY ?EASY ?GO|CONFIRMTKT|RAILYATRI|TRAINMAN|AIR ?INDIA ?EXPRESS|\bAIX\b|ALLIANCE ?AIR|STAR ?AIR|FLYBIG|EMIRATES|QATAR ?AIRWAYS|ETIHAD|SINGAPORE ?AIRLINES|LUFTHANSA|BRITISH ?AIRWAYS|THAI ?AIRWAYS|TREEBO|FABHOTEL|ZOSTEL|\bIHCL\b|TAJ ?HOTELS|MARRIOTT|\bHYATT\b|HILTON|ITC ?HOTELS|LEMON ?TREE|GINGER ?HOTEL|EXPEDIA|TRIVAGO|\bKSRTC\b|\bMSRTC\b|\bGSRTC\b|\bAPSRTC\b|\bTSRTC\b|\bUPSRTC\b|\bRSRTC\b|HRTC|ZINGBUS|INTRCITY|FLIXBUS|NUEGO/, 'Travel'),
  // electricity, gas, water, society
  R(/TANGEDCO|\bTNEB\b|TNPDCL|\bTPDDL\b|\bBRPL\b|\bBYPL\b|\bCESC\b|\bKSEB\b|APSPDCL|APEPDCL|APCPDCL|TSSPDCL|TSNPDCL|WBSEDCL|\bMPEZ\b|MPPKVVCL|MPMKVVCL|\bJVVNL\b|\bAVVNL\b|\bJDVVNL\b|\bPSPCL\b|\bUPPCL\b|\bPVVNL\b|\bMVVNL\b|\bDVVNL\b|\bPUVVNL\b|\bKESCO\b|\bDGVCL\b|\bMGVCL\b|\bPGVCL\b|\bUGVCL\b|\bNBPDCL\b|\bSBPDCL\b|\bCSPDCL\b|HESCOM|GESCOM|MESCOM|CHESCOM|NOIDA ?POWER|\bNPCL\b|\bTORRENT\b|GUJARAT ?GAS|ADANI ?(TOTAL )?GAS|SABARMATI ?GAS|GREEN ?GAS|\bMNGL\b|MYGATE|NOBROKERHOOD|APNA ?COMPLEX|\bNBH\b|\bEB ?BILL\b/, 'Bills & Utilities'),
  // phone, internet, TV
  R(/YOU ?BROADBAND|\bSPECTRA\b|ALLIANCE ?BROADBAND|\bGTPL\b|DEN ?NETWORKS|SUN ?DIRECT|DISH ?TV|\bD2H\b|AIRTEL ?XSTREAM|\bJIOFIBER|\bJIO ?AIRFIBER/, 'Mobile & Internet'),
  // learning
  R(/PHYSICS ?WALLAH|\bUPGRAD\b|SIMPLILEARN|GREAT ?LEARNING|\bSCALER\b|INTERVIEWBIT|\bALLEN\b|\bAAKASH\b|FIITJEE|TOPPR|CUEMATH|WHITEHAT|BRAINLY|EXTRAMARKS|NEXT ?EDUCATION|\bLEAD ?SCHOOL|SCHOOL ?FEES|PUBLIC ?SCHOOL|VIDYALAYA|VIDYA ?MANDIR|CONVENT/, 'Education'),
  // insurance (not the word "premium" alone)
  R(/ICICI ?LOMBARD|TATA ?AIG|HDFC ?ERGO|RELIANCE ?GENERAL|SBI ?GENERAL|MANIPAL ?CIGNA|ADITYA ?BIRLA ?HEALTH|NEW ?INDIA ?ASSURANCE|UNITED ?INDIA ?INS|ORIENTAL ?INS|NATIONAL ?INSURANCE|KOTAK ?LIFE|PNB ?METLIFE|CANARA ?HSBC|\bAVIVA\b|EDELWEISS ?TOKIO|FUTURE ?GENERALI|CHOLA ?MS|ROYAL ?SUNDARAM|IFFCO ?TOKIO|LIBERTY ?GENERAL|\bZUNO\b|\bRENEWBUY\b/, 'Insurance'),
  // pay later and loans
  R(/LAZYPAY|\bSIMPL\b|\bSLICE\b|ZESTMONEY|MONEY ?VIEW|\bFIBE\b|EARLY ?SALARY|\bCASHE\b|MPOKKET|PAYSENSE|INDIALENDS|HOME ?LOAN|CAR ?LOAN|PERSONAL ?LOAN|GOLD ?LOAN|MUTHOOT|MANAPPURAM|\bLOAN ?EMI\b|\bEMI\b/, 'EMI & Loans'),
  // personal care
  R(/LAKME ?SALON|\bNATURALS ?SALON|JAWED ?HABIB|\bENRICH ?SALON|\bYLG\b|TONI ?&? ?GUY|BODYCRAFT|LOOKS ?SALON/, 'Personal Care'),
];
